# Generated by Django 4.2.6 on 2023-10-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracticeHub', '0002_alter_article_name_alter_noun_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='noun',
            name='meaning',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
