# Generated by Django 4.2.6 on 2023-10-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracticeHub', '0003_noun_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='noun',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
