# Generated by Django 4.2.6 on 2023-10-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracticeHub', '0005_verb_alter_noun_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='meaning',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
