# Generated by Django 4.2.6 on 2023-12-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracticeHub', '0007_verb_perfect_form_verb_perfect_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='noun',
            name='examples',
            field=models.TextField(blank=True, null=True),
        ),
    ]
