# Generated by Django 4.2.6 on 2024-01-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracticeHub', '0008_noun_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abbr',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
